server:
  #  启动端口
  port: 8083

spring:
  shardingsphere:
    datasource:
      #      定义数据源
      names: db1,db2
      #      配置数据源
      db1:
        #        type: com.alibaba.druid.pool.xa.DruidXADataSource
        type: com.alibaba.druid.pool.DruidDataSource
        url: 'jdbc:mysql://47.110.49.234:3306/ums_dev?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai'
        #        username: 'ums_dev'
        #        password: 'ums_1234'
        username: 'root'
        password: 'wyq1234'
        initial-size: 5
        min-idle: 10
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 2000
        min-evictable-idle-time-millis: 600000
        max-evictable-idle-time-millis: 900000
        validation-query: "select 1"
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        keep-alive: true
        phy-max-use-count: 1000
        filter: "stat"
        driver-class-name: com.mysql.jdbc.Driver
      db2:
        #        type: com.alibaba.druid.pool.xa.DruidXADataSource
        type: com.alibaba.druid.pool.DruidDataSource
        url: 'jdbc:mysql://47.110.49.234:3307/product_dev?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai'
        #        username: 'product_dev'
        #        password: 'product_1234'
        username: 'root'
        password: 'wyq1234'
        initial-size: 5
        min-idle: 10
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 2000
        min-evictable-idle-time-millis: 600000
        max-evictable-idle-time-millis: 900000
        validation-query: "select 1"
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        keep-alive: true
        phy-max-use-count: 1000
        filter: "stat"
        driver-class-name: com.mysql.jdbc.Driver
    sharding:
      tables:
        ums_member:
          #            ums_member分布在db1上
          actual-data-nodes: db1.ums_member
        p_order:
          #            p_order分布在db2上
          actual-data-nodes: db2.p_order
    props:
      sql:
        #          打印sql
        show: true
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 47.110.49.234
    port: 6379
    password: wyq1234
mybatis:
  mapper-locations: classpath:/mapper/**
  configuration:
    map-underscore-to-camel-case: true



logging:
  level.org.springframework.jdbc.datasource.DataSourceTransactionManager: debug
  level.com.atomikos.datasource.xa: debug
  level.com.atomikos.jdbc: true
